(cl:defpackage ar_localizer-srv
  (:use )
  (:export
   "GENERATELOCATIONS"
   "<GENERATELOCATIONS-REQUEST>"
   "GENERATELOCATIONS-REQUEST"
   "<GENERATELOCATIONS-RESPONSE>"
   "GENERATELOCATIONS-RESPONSE"
  ))

